const String slash = '/';
const ROUTE_SPLASH = "${slash}splash";
const ROUTE_LOGIN = "${slash}login";
const ROUTE_REGISTER = "${slash}register";
const ROUTE_HOME = "${slash}Home";
const ROUTE_CATEGORIES = "${slash}Categories";
const ROUTE_ADDITEMS = "${slash}AddItems";
const ROUTE_ADDPURCHASE = "${slash}AddPurchase";
const ROUTE_PURCHASE = "${slash}Purchase";
const ROUTE_EMPLOYEE = "${slash}Employee";
const ROUTE_ATTENDANCE = "${slash}Attendance";
const ROUTE_PAYMENT = "${slash}Payment";
const ROUTE_POS = "${slash}pos";
const ROUTE_TICKETLIST = "${slash}ticketList";
const ROUTE_ADJUSTMENT = "${slash}adjustment";
const ROUTE_ADMINACCESS = "${slash}adminAccess";
//pref data
const String AUTH_CODE = 'AUTH_CODE';
const String ROLE = 'ROLE';